language: ruby
script: rspec spec -b
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-2.2
  - jruby-18mode
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system 2.1.11 #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
